name: Maven Release

'on':
  release:
    types: [published]

jobs:
  publish:
    name: Build and Upload JARs
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Java
        uses: actions/setup-java@v3
        with:
          java-version: '21'
          distribution: temurin

      - name: Set maven project version
        run: mvn -B versions:set -DnewVersion=${{ github.event.release.tag_name }} -DgenerateBackupPoms=false

      - name: Build and package Maven project
        run: mvn clean package -DskipTests

      - name: Upload to release
        uses: softprops/action-gh-release@v1
        with:
          files: target/PollMaster-${{ github.event.release.tag_name }}.jar
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

